# Generated by Django 3.1.7 on 2021-03-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('category', models.CharField(max_length=45)),
                ('location', models.CharField(max_length=100)),
                ('regdate', models.DateTimeField()),
            ],
        ),
    ]
